# ETL pipeline Docker image
# TODO: Configure Python ETL container

FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml .
COPY src/ src/

RUN pip install --no-cache-dir -e .

CMD ["python", "-m", "src.pipelines.run_full_pipeline"]
